eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
      enabled: true
      lease:
         duration: 5
      
      
server:
  port: 8098
  
spring:
   application:
      name: mobile-service